// Code generated by gen-types. DO NOT EDIT.

export type AboutProps = {
  count: number;
}

export type CalendarProps = {
}

export type IndexProps = {
  name: string;
}

export type LoggedProps = {
  message: string;
}

export type LoginProps = {
}

export type NotFoundProps = {
  path: string;
}

export type UsersProps = {
  users: User[];
  totalCount: number;
}

export type User = {
  id: number;
  name: string;
  email: string;
  role: string;
}

