package pkgs

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"reflect"
	"strings"
	"text/template"
)

type EntryPointGenerator struct {
	workdir  string
	rootTmpl *template.Template

	entryPoints map[string]struct{}
	propsTypes  []reflect.Type
}

func NewEntryPointGenerator(workdir string) *EntryPointGenerator {
	return &EntryPointGenerator{
		workdir:     workdir,
		rootTmpl:    template.Must(template.New("root").Parse(entryPointTmpl)),
		entryPoints: make(map[string]struct{}),
		propsTypes:  make([]reflect.Type, 0),
	}
}

type EntryPointGeneratorContextKey struct{}

func WithEntryPointGenerator(ctx context.Context, generator *EntryPointGenerator) context.Context {
	return context.WithValue(ctx, EntryPointGeneratorContextKey{}, generator)
}

func EntryPointGeneratorFromContext(ctx context.Context) (*EntryPointGenerator, error) {
	value := ctx.Value(EntryPointGeneratorContextKey{})
	if value == nil {
		return nil, errors.New("entry point generator not found in context")
	}
	generator, ok := value.(*EntryPointGenerator)
	if !ok {
		return nil, errors.New("invalid entry point generator type in context")
	}
	return generator, nil
}

func (r *EntryPointGenerator) Generate(entryPoint string) error {
	if _, ok := r.entryPoints[entryPoint]; ok {
		return errors.New("entry point already exists")
	}

	r.entryPoints[entryPoint] = struct{}{}

	p := filepath.Join(r.workdir, entryPoint)

	err := os.MkdirAll(path.Dir(p), os.ModePerm)
	if err != nil {
		return err
	}

	f, err := os.Create(p)
	if err != nil {
		return err
	}
	defer f.Close()

	err = r.rootTmpl.Execute(f, map[string]interface{}{
		"EntryPoint": entryPoint,
	})
	if err != nil {
		return err
	}

	return nil
}

const entryPointTmpl = `
import { StrictMode } from "react";
import { createRoot } from 'react-dom/client'
import App from '~/{{ .EntryPoint }}'


createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App {...(window.APP_PROPS || {})}/>
  </StrictMode>
)
`

func (r *EntryPointGenerator) GenerateEntryPointConfig() error {
	m := make(map[string]string, len(r.entryPoints))

	for entryPoint := range r.entryPoints {
		m[entryPoint] = filepath.Join(r.workdir, entryPoint)
	}

	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}

	err = os.WriteFile("entries.gen.json", b, 0644)
	if err != nil {
		return err
	}

	return nil
}

func (r *EntryPointGenerator) RegisterPropsType(rt reflect.Type) {
	r.propsTypes = append(r.propsTypes, rt)
}

func (r *EntryPointGenerator) GenerateTypeScriptPropsTypes() error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen-types. DO NOT EDIT.\n\n")

	generatedTypes := make(map[reflect.Type]bool)
	var typeDefinitions []string

	var processType func(t reflect.Type) string
	processType = func(t reflect.Type) string {
		for t.Kind() == reflect.Ptr {
			t = t.Elem()
		}

		switch t.Kind() {
		case reflect.String:
			return "string"
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Float32, reflect.Float64:
			return "number"
		case reflect.Bool:
			return "boolean"
		case reflect.Slice, reflect.Array:
			return processType(t.Elem()) + "[]"
		case reflect.Map:
			keyType := processType(t.Key())
			valueType := processType(t.Elem())
			return "{ [key: " + keyType + "]: " + valueType + " }"
		case reflect.Struct:
			if t.PkgPath() == "time" && t.Name() == "Time" {
				return "string"
			}

			typeName := t.Name()
			if typeName == "" {
				// Anonymous struct
				var s bytes.Buffer
				s.WriteString("{\n")
				for i := range t.NumField() {
					field := t.Field(i)
					if !field.IsExported() {
						continue
					}
					tag := field.Tag.Get("json")
					fieldName := field.Name
					if tag != "" && tag != "-" {
						parts := strings.Split(tag, ",")
						fieldName = parts[0]
					}
					s.WriteString(fmt.Sprintf("  %s: %s;\n", fieldName, processType(field.Type)))
				}
				s.WriteString("}")
				return s.String()
			}

			if !generatedTypes[t] {
				generatedTypes[t] = true
				var s bytes.Buffer
				s.WriteString(fmt.Sprintf("export type %s = {\n", typeName))
				for i := range t.NumField() {
					field := t.Field(i)
					if !field.IsExported() {
						continue
					}
					tag := field.Tag.Get("json")
					fieldName := field.Name
					if tag != "" && tag != "-" {
						parts := strings.Split(tag, ",")
						fieldName = parts[0]
					}
					s.WriteString(fmt.Sprintf("  %s: %s;\n", fieldName, processType(field.Type)))
				}
				s.WriteString("}\n")
				typeDefinitions = append(typeDefinitions, s.String())
			}
			return typeName
		case reflect.Interface:
			return "any"
		default:
			return "any"
		}
	}

	for _, rt := range r.propsTypes {
		processType(rt)
	}

	for i := len(typeDefinitions) - 1; i >= 0; i-- {
		buf.WriteString(typeDefinitions[i])
		buf.WriteString("\n")
	}

	return os.WriteFile("types.gen.ts", buf.Bytes(), os.ModePerm)
}
